owner: RavelloH 

repo: sitemonitor # The name of this repository

sites:
  - name: GithubSite
    url: https://ravelloh.github.io
  - name: GiteeSite
    url: https://ravelloh.gitee.io
  - name: JsSite
    url: https://ravelloh.js.org
  - name: TestSite
    url: http://web1671.hao321.ml
  - name: TencentSite
    url: https://website-0ggrccba61ac6225-1304791521.tcloudbaseapp.com
  - name: CNAME
    url: https://ravello-h.github.io
  - name: StudioSite 
    url: https://xeocnet-studio.github.io

status-website:
  baseUrl: /sitemonitor
  name: Upptime
  navbar:
    - title: State
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
