owner: RavelloH 

repo: sitemonitor # The name of this repository

sites:
  - name: GithubSite
    url: https://ravelloh.github.io
  - name: GiteeSite
    url: https://ravelloh.gitee.io
  - name: JsSite
    url: https://ravelloh.js.org
  - name: CNAME
    url: https://ravello-h.github.io
  - name: StudioSite 
    url: https://xeocnet-studio.github.io
  - name: VercelSiteNo1
    url: https://ravelloh-ravelloh.vercel.app
  - name: VercelSiteNo2
    url: https://ravelloh.vercel.app
  - name: VercelDevSite
    url: https://ravelloh-p1m2hxads-ravelloh.vercel.app

status-website:
  baseUrl: /sitemonitor
  name: Upptime
  navbar:
    - title: State
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
