name: ci

on:

  push:

    branches:

      - master

  schedule:

    - cron: "0 */3 */3 * 0,5,6"

jobs:

  autogreen:

    runs-on: ubuntu-latest

    steps:

      - name: Clone repository

        uses: actions/checkout@v2

      - name: Refresh

        run: |

          git config --local user.email "hyh20060327@qq.com"

          git config --local user.name "RavelloH"

          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

          git pull --rebase

          git commit --allow-empty -m "Site states refresh."

          git push
